### ISSUE TITLE
SendFileExtensions should be in Http.Extensions

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#221]
https://github.com/aspnet/StaticFiles/blob/dev/src/Microsoft.AspNet.StaticFiles/SendFileExtensions.cs

**Comment by Praburaj** [comment]
This file seems to have one `IApplicationBuilder` extension (`UseSendFileFallback`) rather than an extension on top of Request or response related objects. @davidfowl do you really want to move this to `Microsoft.AspNet.Http.Extensions` packages? For every other package the `IApplicationBuilder` extensions live in the respective packages.

**Comment by davidfowl** [comment]
Oops wrong file:
https://github.com/aspnet/StaticFiles/blob/dev/src/Microsoft.AspNet.StaticFiles/SendFileResponseExtensions.cs

**Comment by Praburaj** [comment]
got it.
