### ISSUE TITLE
Should StringValues implement Equals?

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpAbstractions#384]
StringValues does not currently implement Equals (or GetHashCode).  MVC implements their own wrapper that has Equals. If so, what should be considered equal?
"string" == new[] { "string" }?
string.Empty == null?
null == new[] { null }?
"value1,value2" == new[] { "value1", "value2" }?
Ordinal?

**Comment by atifaziz** [comment]
Since `StringValues` is logically just an array of strings with some internal optimizations, its equality and hashing should behave like that of an array when being checked for [structural equality](https://msdn.microsoft.com/en-us/library/system.collections.istructuralequatable(v=vs.110).aspx). That would provide the least surprises and yet still permit some customization when needed (e.g. ignore case when comparing each element).

**Comment by glennc** [comment]
@Tratcher can you round up @lodejard and @davidfowl to get an answer for this now-ish?

**Comment by davidfowl** [comment]
@rynowak we did this right?

**Comment by khellang** [comment]
@davidfowl https://github.com/aspnet/Common/commit/35333347a6c0c4ccc6cbe3723f17e01ab2bd543a

**Comment by rynowak** [comment]
@davidfowl - it implements `.Equals`. We should think about removing some of the overloaded `==` operators. Right now if you try to compare with null you get an error about ambiguity when you should get the 'Hey, it's a struct buddy' error.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2726
