### ISSUE TITLE
Rename Microsoft.Framework.* to Microsoft.Extensions.*

### ISSUE THREAD

**Issue by Eilon** [aspnet/HttpAbstractions#422]
Need to rename assemblies and namespaces from `Microsoft.Framework.*` to `Microsoft.Extensions.*`.

Once the change is committed, please post an issue in the https://github.com/aspnet/Announcements/issues/ repo that links back to this issue.

**Comment by pranavkm** [comment]
What are they extending?

**Comment by khellang** [comment]
@pranavkm Microsoft, of course! :wink:

TBH, `Microsoft.Extensions.*` sounds like the same old generic dumping ground as `Microsoft.Framework.*` :stuck_out_tongue_winking_eye:

**Comment by Eilon** [comment]
They're extending the platform in new ways for new features (DI, logging, config, etc.).

**Comment by pranavkm** [comment]
https://github.com/aspnet/HttpAbstractions/commit/61466af7a38497ae25d538e5eb0f4cbcb6f303a0

**Comment by Antaris** [comment]
This seems a little odd.

The previous `Microsoft.Framework` made a bit more sense, because they are defining `Framework` items, the core collection of types used as the "framework". I personally don't think `Extensions` works the same way, because that suggests they are extending *something*. The reality is they don't, they are the "framework` itself? and Microsoft isn't the framework, or the platform, so how are they extending "Microsoft"?

**Comment by Eilon** [comment]
@Antaris it was a tough choice, but it's the one that we overall liked the most.
