### ISSUE TITLE
Dotnet all the things?

### ISSUE THREAD

**Issue by adamhathcock** [aspnet/HttpAbstractions#432]
Is there a reason Microsoft.Extensions.WebEncoders.Core (and likely most other things in this repo) aren't targetting DOTNET as opposed to DNXCORE50?

**Comment by Tratcher** [comment]
FYI Microsoft.Extensions.WebEncoders.Core is being replaced by System.Test.Encoding.Web. See #391.

I won't comment on the others.

**Comment by Eilon** [comment]
@adamhathcock regarding the encoders type in particular, see @Tratcher 's comment.

Regarding the `dotnet` target in general, we're working on some improvements to how that works (we think it'll be *much* easier and *much* more powerful), so just stay tuned and you'll hear all the latest. Expect a lot more things to use a `dotnet` target instead of DNX-specific.
