### ISSUE TITLE
StringValues in RequestCookiesCollection

### ISSUE THREAD

**Issue by DaBackman** [aspnet/HttpAbstractions#447]
Hi,

I did notice that you updated the signature of RequestCookiesCollection.this[string key] in beta 8 from returning String to StringValues.
Why is that? 
Unless I'm misstaken, a cookie value cannot be multiple strings, only null or exactly one string, so just returning a string would make most sense.

Thank you!

**Comment by khellang** [comment]
This is because `RequestCookiesCollection` implements [`IReadableStringCollection`](https://github.com/aspnet/HttpAbstractions/blob/7ed6a6cb578ca9a18c44751acca2257d752c0699/src/Microsoft.AspNet.Http.Abstractions/IReadableStringCollection.cs), which is common for headers, query, forms, etc.

If you want to get a single `string`, you can use [`RequestCookiesCollection.Get(string key)`](https://github.com/aspnet/HttpAbstractions/blob/7ed6a6cb578ca9a18c44751acca2257d752c0699/src/Microsoft.AspNet.Http/RequestCookiesCollection.cs#L58-L62). This is also the method used by the indexer internally :smile:

**Comment by DaBackman** [comment]
So the way to work with cookies would be something similar:

```c#
var cookies = (RequestCookiesCollection) HttpContext.Request.Cookies;
var cookieValue = cookies.Get("myKey");
```
or possibly:

```c#
var values = HttpContext.Request.Cookies["myKey"];
var cookieValue = values.FirstOrDefault(); // can only be one or null
```

Is it safe to always cast IReadableStringCollection to RequestCookiesCollection when working with HttpRequest in HttpContext?

**Comment by khellang** [comment]
Oh, I didn't realize that `HttpContext` exposed `public abstract IReadableStringCollection Cookies { get; set; }`. That makes things worse :cry:

**Comment by khellang** [comment]
@DaBackman `StringValues` is implicitly convertible to `string`, so you could do `var cookieValue = HttpContext.Request.Cookies["myKey"];` :smile:

**Comment by DaBackman** [comment]
Ahh, I see.
Thank you!
