### ISSUE TITLE
Move HttpContextAccessor from .Internal namespace

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#549]
If users want to use this API they need to call

```C#
services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
```

Today this requires adding `using Microsoft.AspNet.Http.Internal;`

**Comment by dougbu** [comment]
Suggest we take this further and move everything or almost everything our own repos depend on from `.Internal` into a public namespace. Right now Antiforgery, BasicMiddleware, CORS, Diagnostics, Entropy, Hosting, Identity, ... all use HttpAbstraction's `.Internal` namespaces. And all such namespaces defined in this repo except `Microsoft.AspNetCore.Http.Authentication.Internal` have references from other repos.

**Comment by muratg** [comment]
@dougbu Good to close?

**Comment by dougbu** [comment]
No. I'm doing more of this in concert w/ the #592 fix at @davidfowl's urging.

**Comment by dougbu** [comment]
Taking this one because we're tying fix together w/ #592 i.e. will do one set of reaction PRs.

**Comment by dougbu** [comment]
Will move the following types to `Microsoft.AspNetCore.Http`. All of these are currently used in other aspnet repo's product code.

- `DefaultHttpContext`
- `FormCollection` (though not mainstream, necessary for some scenarios e.g. handling a form-URL-encoded response as in aspnet/Security)
- `HeaderDictionary`
- `HttpContextAccessor` (remains the most important of these changes because it's necessary for any use of the `IHttpContextAccessor` feature e.g. in aspnet/Identity)
- `HttpContextFactory`

Will also move files around in the repo so the remaining `Microsoft.AspNetCore.Http.Internal` classes are in an `Internal` sub-folder.

**Comment by dougbu** [comment]
- 6725d68
- aspnet/Hosting@6e87b51
- aspnet/KestrelHttpServer@c828faf
- aspnet/WebListener@84c8975
- aspnet/IISIntegration@52e5ccd
- aspnet/CORS@5a3ea74
- aspnet/Routing@67f4243
- aspnet/StaticFiles@74d2c13
- aspnet/Antiforgery@65a2b8d
- aspnet/Diagnostics@f1a0243
- aspnet/Security@16a0482
- aspnet/Mvc@6bf25ce
- aspnet/Identity@b2bf1a4
- aspnet/Entropy@9da3ca9
- aspnet/MusicStore@20a24a2
