### ISSUE TITLE
[MultipartReaderStream] Misleading exception message

### ISSUE THREAD

**Issue by Eilon** [aspnet/HttpAbstractions#736]
_From @mabakay on November 16, 2016 22:53_

When multipart/form-data request is malformed for instance (missing double dash at boundary start):

> 9051914041544843365972754266
> Content-Disposition: form-data; name="text"
> 
> text default
> --9051914041544843365972754266--

and request body is greater than default limit for _HeadersLengthLimit_ (which is 16KB now), user get exception message of "**Multipart body length limit 16384 exceeded.**"

`MultipartReaderStream.cs #166`

_Copied from original issue: aspnet/Mvc#5534_

**Comment by Eilon** [comment]
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.WebUtilities/MultipartReaderStream.cs#L166

**Comment by muratg** [comment]
Assigning to @Tratcher for investigation.

**Comment by Tratcher** [comment]
The confusion here is that multipart forms don't start with the first boundary, there can be an arbitrary amount of data prior to the first boundary.
```
Hello world, how are you? This is preamble data
--9051914041544843365972754266
Content-Disposition: form-data; name="text"

text default
--9051914041544843365972754266--
```
Because the boundary is not correctly formatted in your example, that data is all parsed as part of the initial 'body' and so the body limit applies. Note that the limits can't currently be configured for this initial section.
https://github.com/aspnet/HttpAbstractions/blob/594f55947f4c1d0a9d3122e3f39bcfa81199b12a/src/Microsoft.AspNetCore.WebUtilities/MultipartReader.cs#L48-L50
