### ISSUE TITLE
Unable to upload file greater than 2GB in size

### ISSUE THREAD

**Issue by kagoyal** [aspnet/HttpAbstractions#766]
I am trying to upload file greater than 2GB using multipart formdata. 

The issue I am observing is after 2GB upload, read of input stream gets stuck and process hangs.
Microsoft.AspNetCore.Server.Kestrel version we are using is "1.1.0".

HTTP request’s response never come back and timesout after one hour (execution time we have set).
I have modified IIS post limits for upto 4GB, also in ConfigureServices –

                services.Configure<FormOptions>(x =>
                {
                    x.MultipartBodyLengthLimit = 4294967296; 
                });

I am following the sample here - https://github.com/aspnet/Docs/tree/master/aspnetcore/mvc/models/file-uploads/sample/FileUploadSample to read multipart data.

Please let me know if any more information is required to debug this, or if this is expected behavior.

**Comment by benaadams** [comment]
What's the upload speed/transfer rate?

**Comment by kagoyal** [comment]
I am able to upload approx. 1.8 GB of data in about 30-35 seconds.

**Comment by blowdart** [comment]
Well the timeout is working, so not a security concern, just a weird bug. @muratg

**Comment by JunTaoLuo** [comment]
I am able to upload 4GB files when using Kestrel directly but I ran into problems when running it on IIS. I was not able to produce a hang but I do see a 502 failure response. It seems like the connection is being reset and it could be due to ANCM. I filed https://github.com/aspnet/AspNetCoreModule/issues/78.

**Comment by JunTaoLuo** [comment]
I confirmed that ANCM is the module that is producing the 502 error code from the FREB logs. The limit seems to be 2GB for upload file size so there's no way of uploading bigger files when running behind IIS. I'm closing this issue as this is not a restriction in AspNet Core @kagoyal please re-open if you have any additional concerns or comments.

**Comment by JunTaoLuo** [comment]
Re-opening investigation

**Comment by cesarbs** [comment]
We've had a similar issue in Kestrel because we were using and `int` instead of a `long` to keep track of the request body size. Could that be the case here?

**Comment by JunTaoLuo** [comment]
There are a few issues at play here. There is a limit with the Request Filter in IIS which has a limit of UInt32.Max (~4GB) but this filter can be removed. By testing files of different sizes I also found that the request size is limited by ANCM to ~2GB likely limited by int. However, I'm reopening the issue for investigation since I believe the way I'm reproducing the issue is flawed. I was trying streaming uploads from browsers (chrome, firefox, ie, edge) but these browsers seem to automatically add a `Content-Length` header to the request which is not what we want for multipart forms. I'm going to try reproducing this issue with a custom client.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2711
