### ISSUE TITLE
Plus '+' encoded in HTML attributes

### ISSUE THREAD

**Issue by miloush** [aspnet/HttpAbstractions#903]
`<p title="@title">P</p>` where `title = "A+B"` results in `<p title="A&#x2B;B">P</p>`.

Why and how can I prevent that? I have already used WebEncoderOptions to allow all ranges.

**Comment by NTaylorMullen** [comment]
You can avoid this by doing `<p title="@Html.Raw(title)">P</p>`. Razor encodes dynamic content by default.

**Comment by miloush** [comment]
That's alright, I want it to encode the text, but I don't see any reason why it should encode +?

**Comment by NTaylorMullen** [comment]
The `+` encoding is an artifact of how the default `HtmlEncoder` in corefx works. Based on [their code](https://github.com/dotnet/corefx/blob/c3d9361a2422a392336c96a8284a9350bddf01f0/src/System.Text.Encodings.Web/src/System/Text/Encodings/Web/HtmlEncoder.cs#L76) it looks like the `+` symbol is forbidden in order to avoid possible UTF7-based attacks.

If you want  to change this behavior you could replace the default encoder in DI and provide it with different encoding settings: https://github.com/dotnet/corefx/blob/c3d9361a2422a392336c96a8284a9350bddf01f0/src/System.Text.Encodings.Web/src/System/Text/Encodings/Web/HtmlEncoder.cs#L31

**Comment by blowdart** [comment]
Or you could configure the encoder to allow + through, rather than going through all the bother of replacing the encoder.

[This is documented](https://docs.microsoft.com/en-us/aspnet/core/security/cross-site-scripting).

**Comment by miloush** [comment]
@blowdart how would I go about doing that? It seems that the encoder caches the allowed characters in its constructor and overrides it with forbidden characters, with no possibility to configure that, or have I missed something?

**Comment by blowdart** [comment]
Oh indeed you're right, even if you specifically list the ascii parts we're going to treat + as dangerous. Is the encoding causing the hover over to display the encoded value and not the original character?

**Comment by miloush** [comment]
No, it's replacing 1 character with 6, and I happen to have like thousand of them on couple of pages each, so it's making me unhappy.

The UTF-7 attack seems to be only applicable if you don't specify encoding on the page in IE7. While sensible default, it is in my power to set the encoding, so I should be able to allow + through too. (On slightly unrelated note, I can allow + in URL using `<requestFiltering allowDoubleEscaping="true" />`.)

**Comment by blowdart** [comment]
We lean towards secure by default, because it protects the greatest amount of people. If HTTP compression is on then the size increase isn't going to be that bad in our opinion. Unfortunately Taylor's suggestion is going to be the only one that works here, you'll have to spin up a new encoder, probably have it just call the default one and do a replace on the results then shove it in DI

**Comment by miloush** [comment]
Thanks blowdart, I lean towards doing that. I also found it always encodes all the control characters although not all of them have to be encoded (and in case you are serving XHTML as XML you aren't allowed some, encoded or not). I appreciate this isn't easy to get right for everyone, thanks for help!
